// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iushyxumqobzyyvmrkre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1c2h5eHVtcW9ienl5dm1ya3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDQxNzUsImV4cCI6MjA2NTk4MDE3NX0.Z4VNLmOipCN-vyw4sMpwG337h8q19lGEaefwAMFbRfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);